### ISSUE TITLE
Buile errors: undefined reference to `wrapper_ddot_', etc

### ISSUE THREAD

**Issue by yurivict** [susilehtola/erkale#28]
Getting these errors on FreeBSD:
```
cd /usr/ports/science/erkale/work/.build/src/casida && /usr/bin/c++   -I/usr/ports/science/erkale/work/erkale-f1e1ebc/src -I/usr/local/include  -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -o CMakeFiles/erkale_casida.dir/main.cpp.o -c /usr/ports/science/erkale/work/erkale-f1e1ebc/src/casida/main.cpp
liberkale.a(scf-base.cpp.o): In function `determine_occ(arma::Col<double>&, arma::Mat<double> const&, arma::Col<double> const&, arma::Mat<double> const&, arma::Mat<double> const&)':
scf-base.cpp:(.text+0xa4fa): undefined reference to `wrapper_ddot_'
liberkale.a(scf-base.cpp.o): In function `symgroups(arma::Mat<double> const&, arma::Mat<double> const&, std::__1::vector<arma::Mat<double>, std::__1::allocator<arma::Mat<double> > > const&, bool)':
scf-base.cpp:(.text+0x1e0a2): undefined reference to `wrapper_ddot_'
liberkale.a(scf-base.cpp.o): In function `bool arma::auxlib::eig_sym_dc<double, arma::eOp<arma::Mat<double>, arma::eop_neg> >(arma::Col<double>&, arma::Mat<double>&, arma::Base<double, arma::eOp<arma::Mat<double>, arma::eop_neg> > const&)':
scf-base.cpp:(.text._ZN4arma6auxlib10eig_sym_dcIdNS_3eOpINS_3MatIdEENS_7eop_negEEEEEbRNS_3ColIT_EERNS3_IS8_EERKNS_4BaseIS8_T0_EE[_ZN4arma6auxlib10eig_sym_dcIdNS_3eOpINS_3MatIdEENS_7eop_negEEEEEbRNS_3ColIT_EERNS3_IS8_EERKNS_4BaseIS8_T0_EE]+0x624): undefined reference to `wrapper_dsyevd_'
liberkale.a(scf-base.cpp.o): In function `bool arma::auxlib::eig_sym<double, arma::eOp<arma::Mat<double>, arma::eop_neg> >(arma::Col<double>&, arma::Mat<double>&, arma::Base<double, arma::eOp<arma::Mat<double>, arma::eop_neg> > const&)':
scf-base.cpp:(.text._ZN4arma6auxlib7eig_symIdNS_3eOpINS_3MatIdEENS_7eop_negEEEEEbRNS_3ColIT_EERNS3_IS8_EERKNS_4BaseIS8_T0_EE[_ZN4arma6auxlib7eig_symIdNS_3eOpINS_3MatIdEENS_7eop_negEEEEEbRNS_3ColIT_EERNS3_IS8_EERKNS_4BaseIS8_T0_EE]+0x576): undefined reference to `wrapper_dsyev_'
liberkale.a(scf-base.cpp.o): In function `void arma::glue_times::apply_inplace_plus<arma::Op<arma::Mat<double>, arma::op_htrans>, arma::Mat<double> >(arma::Mat<arma::Op<arma::Mat<double>, arma::op_htrans>::elem_type>&, arma::Glue<arma::Op<arma::Mat<double>, arma::op_htrans>, arma::Mat<double>, arma::glue_times> const&, long long)':
scf-base.cpp:(.text._ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx]+0x32f): undefined reference to `wrapper_dgemv_'
scf-base.cpp:(.text._ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx]+0x3ce): undefined reference to `wrapper_dgemv_'
scf-base.cpp:(.text._ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx]+0x468): undefined reference to `wrapper_dgemv_'
scf-base.cpp:(.text._ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx[_ZN4arma10glue_times18apply_inplace_plusINS_2OpINS_3MatIdEENS_9op_htransEEES4_EEvRNS3_INT_9elem_typeEEERKNS_4GlueIS7_T0_S0_EEx]+0x4fc): undefined reference to `wrapper_dgemv_'
liberkale.a(scf-base.cpp.o): In function `void arma::syrk_vec<true, false, true>::apply<double, arma::Mat<double> >(arma::Mat<double>&, arma::Mat<double> const&, double, double)':
scf-base.cpp:(.text._ZN4arma8syrk_vecILb1ELb0ELb1EE5applyIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_[_ZN4arma8syrk_vecILb1ELb0ELb1EE5applyIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_]+0x1e9): undefined reference to `wrapper_ddot_'
liberkale.a(scf-base.cpp.o): In function `void arma::gemm<true, false, false, true>::apply_blas_type<double, arma::Mat<double>, arma::Mat<double> >(arma::Mat<double>&, arma::Mat<double> const&, arma::Mat<double> const&, double, double)':
scf-base.cpp:(.text._ZN4arma4gemmILb1ELb0ELb0ELb1EE15apply_blas_typeIdNS_3MatIdEES4_EEvRNS3_IT_EERKT0_RKT1_S5_S5_[_ZN4arma4gemmILb1ELb0ELb0ELb1EE15apply_blas_typeIdNS_3MatIdEES4_EEvRNS3_IT_EERKT0_RKT1_S5_S5_]+0xf1): undefined reference to `wrapper_dgemm_'
liberkale.a(scf-base.cpp.o): In function `void arma::syrk_vec<true, true, true>::apply<double, arma::Mat<double> >(arma::Mat<double>&, arma::Mat<double> const&, double, double)':
scf-base.cpp:(.text._ZN4arma8syrk_vecILb1ELb1ELb1EE5applyIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_[_ZN4arma8syrk_vecILb1ELb1ELb1EE5applyIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_]+0x1fa): undefined reference to `wrapper_ddot_'
liberkale.a(scf-base.cpp.o): In function `void arma::syrk<true, true, false>::apply_blas_type<double, arma::Mat<double> >(arma::Mat<double>&, arma::Mat<double> const&, double, double)':
scf-base.cpp:(.text._ZN4arma4syrkILb1ELb1ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_[_ZN4arma4syrkILb1ELb1ELb0EE15apply_blas_typeIdNS_3MatIdEEEEvRNS3_IT_EERKT0_S5_S5_]+0x1c2): undefined reference to `wrapper_dsyrk_'
```

**Comment by susilehtola** [comment]
The problem is with Armadillo. You're not linking to the BLAS/LAPACK libraries.

Add ```-DLAPACK_LIBRARIES="${LAPACK}" -DBLAS_LIBRARIES="${LAPACK}" ``` to the CMake command. Don't use reference BLAS or LAPACK as it is orders of magnitude slower than optimized implementations. The sequential version should be linked with a sequential BLAS/LAPACK library and the OpenMP version with an OpenMP BLAS/LAPACK library; on Fedora these are available as -lopenblas and -lopenblaso, respectively.

**Comment by yurivict** [comment]
Adding ```-DLAPACK_LIBRARIES=-lopenblas -DBLAS_LIBRARIES=-lopenblasp``` to cmake arguments didn't help. Both ```openblas``` and ```erkale``` are non-OpenMP.

**Comment by susilehtola** [comment]
```-DLAPACK_LIBRARIES=-lopenblas -DBLAS_LIBRARIES=-lopenblasp``` makes no sense, it should be the same library.

Try adding
```
 add_definitions(-DARMA_DONT_USE_WRAPPER)
```
in CMakeLists.txt. It looks like your build wants to use the Armadillo wrapper library that has never made any sense to me.

**Comment by yurivict** [comment]
This worked, thanks!

**Comment by yurivict** [comment]
Now I am trying the ```OpenMP``` version and the problem still exists with ```OpenMP```:
```
[ 62%] Linking CXX executable erkale_slaterfit_omp
cd /usr/ports/science/erkale/work-parallel/.build/src/slaterfit && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/erkale_slaterfit.dir/link.txt --verbose=1
/usr/local/bin/clang++60  -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include -fopenmp=libomp -O2 -pipe -fno-omit-frame-pointer -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer  -isystem /usr/local/include   -Wl,-rpath=/usr/local/lib/gcc7  -L/usr/local/lib/gcc7 -B/usr/local/bin -fstack-protector -L/usr/local/lib CMakeFiles/erkale_slaterfit.dir/main.cpp.o  -o erkale_slaterfit_omp  -L/usr/local/lib -Wl,-rpath,/usr/ports/science/erkale/work-parallel/.build/src:/usr/local/lib: ../liberkale_omp.so.0.1.0 -lrt /usr/local/lib/libgsl.so -lgoto2 -lint -lderiv /usr/local/lib/libxc.so /usr/local/lib/libhdf5.so /usr/local/lib/libsz.so -lz -lm 
--- src/completeness/CMakeFiles/erkale_copt_plateau.dir/all ---
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_zherk_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_zgemm_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dsyev_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dgemm_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dgesdd_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_ddot_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_zgemv_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dnrm2_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dsyevd_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dgemv_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dsyrk_'
../liberkale_omp.so.0.1.0: undefined reference to `wrapper_dgesvd_'
```

```openblas``` is built with ```OpewnMP=ON```.

**Comment by susilehtola** [comment]
You have the same problem as before: Armadillo is trying to use the wrapper library. Don't use separate source directories, you can compile both versions in the same source tree with out-of-root builds.

**Comment by yurivict** [comment]
I am working on the FreeBSD port. It should have 2 flavors: ```sequential``` and ```parallel```.
```add_definitions(-DARMA_DONT_USE_WRAPPER)``` fixed this problem with ```sequential```  build. ```parallel``` should build separately, because they don't depend on each other.

Is there any way to solve this for standalone ```parallel``` build?

**Comment by susilehtola** [comment]
Yes, they build separately, but you can have the same source tree. Your problem should have been fixed, there's something else wrong with your build system. I have had no problems whatsoever building ERKALE in either sequential or parallel versions.

I repeat my previous statement: you aren't using Armadillo properly. You need the -DARMA_DONT_USE_WRAPPER definition in your OpenMP build too. You don't have it in the compile command, meaning you aren't doing what I have told you before.
